import { FormEvent, useEffect, useState } from 'react';
import { BookOpen, Download, FilePlus2, History, Mail, Pencil, Plus, RefreshCw, Send, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useToast } from '../components/Toast';
import { EmptyState, PageHeader, Spinner } from '../components/ui';
import { api, LogoKalemCatalogItem, LogoKalemQuote, LogoKalemRevision, QuoteActivity, QuoteActivityType, QuoteStatus } from '../lib/api';

const statusLabels: Record<QuoteStatus, string> = { DRAFT: 'Taslak', SENT: 'Gönderildi', FOLLOW_UP: 'Takip', MEETING: 'Görüşme', NEGOTIATION: 'Müzakere', ACCEPTED: 'Kabul', REJECTED: 'Ret' };
const blankCatalog: Omit<LogoKalemCatalogItem, 'id'> = { code: '', category: 'Logo', nameTr: '', nameAz: '', nameEn: '', descriptionTr: '', unit: 'Adet', billingPeriod: 'ONE_TIME', defaultPrice: '0', currency: 'USD', active: true, sortOrder: 0 };

export function LogoKalemQuotesPage() {
  const [tab, setTab] = useState<'quotes' | 'catalog'>('quotes');
  const [quotes, setQuotes] = useState<LogoKalemQuote[]>([]);
  const [catalog, setCatalog] = useState<LogoKalemCatalogItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [process, setProcess] = useState<LogoKalemQuote | null>(null);
  const [catalogEdit, setCatalogEdit] = useState<LogoKalemCatalogItem | 'new' | null>(null);
  const toast = useToast(); const navigate = useNavigate();
  const reload = () => { setLoading(true); Promise.all([api.logoKalem.list(), api.logoKalem.catalog()]).then(([q, c]) => { setQuotes(q); setCatalog(c); }).catch((e) => toast.error(e instanceof Error ? e.message : String(e))).finally(() => setLoading(false)); };
  useEffect(reload, []);

  async function send(quote: LogoKalemQuote) {
    if (!window.confirm(`${quote.customerName} için aktif revizyon e-posta ile gönderilsin mi? Gönderilen revizyon kilitlenecektir.`)) return;
    setBusy(quote.id); try { await api.logoKalem.send(quote.id); toast.success('Teklif gönderildi ve revizyon kilitlendi'); reload(); } catch (e) { toast.error(e instanceof Error ? e.message : String(e)); } finally { setBusy(null); }
  }
  async function revise(quote: LogoKalemQuote) {
    setBusy(quote.id); try { await api.logoKalem.newRevision(quote.id); toast.success('Yeni revizyon oluşturuldu'); navigate(`/logo-kalem-quotes/${quote.id}/edit`); } catch (e) { toast.error(e instanceof Error ? e.message : String(e)); } finally { setBusy(null); }
  }

  return <>
    <PageHeader eyebrow="Bağımsız satış modülü" title="Logo-Kalem Teklifler" description="Logo ve Kalem ürünlerini katalogdan seçin, çok dilli kurumsal PDF hazırlayın, revizyonları ve satış sürecini tek yerden izleyin." actions={<button onClick={() => navigate('/logo-kalem-quotes/new')}><FilePlus2 size={16} /> Yeni Teklif</button>} />
    <div className="lk-tabs" role="tablist"><button className={tab === 'quotes' ? 'active' : ''} onClick={() => setTab('quotes')}><History size={16} /> Teklifler</button><button className={tab === 'catalog' ? 'active' : ''} onClick={() => setTab('catalog')}><BookOpen size={16} /> Ürün Kataloğu</button></div>
    {loading ? <Spinner /> : tab === 'quotes' ? <section>
      {quotes.length === 0 ? <EmptyState message="Henüz Logo-Kalem teklifi hazırlanmadı." /> : <div className="table-wrap lk-table"><table><thead><tr><th>Teklif / Revizyon</th><th>Müşteri</th><th>Yatırım</th><th>Durum</th><th>Son hareket</th><th>İşlemler</th></tr></thead><tbody>{quotes.map((q) => {
        const r = q.activeRevision; const number = `${q.baseNumber}-R${String(r?.revisionNumber ?? 0).padStart(2, '0')}`;
        return <tr key={q.id}><td><strong>{number}</strong><small>{r?.projectTitle}</small><small>{r?.language.toUpperCase()} · {r?.lockedAt ? 'Kilitli snapshot' : 'Düzenlenebilir taslak'}</small></td><td><strong>{q.customerName}</strong><small>{q.contactName}</small><small>{q.contactEmail}</small></td><td><strong>{r?.mainTotal ?? '0.00'} {r ? 'USD' : ''}</strong><small>Bakım {r?.maintenanceTotal ?? '0.00'} · LEM {r?.lemTotal ?? '0.00'}</small></td><td><span className={`badge ${q.status}`}>{statusLabels[q.status]}</span>{q.sentAt && <small>{new Date(q.sentAt).toLocaleString('tr-TR')}</small>}</td><td>{q.lastActivity ? <><strong>{q.lastActivity.note}</strong><small>{new Date(q.lastActivity.activityAt).toLocaleString('tr-TR')}</small></> : <small>Henüz hareket yok</small>}</td><td><div className="action-cell"><a className="button ghost" href={api.logoKalem.pdfUrl(q.id)} target="_blank" rel="noreferrer"><Download size={14} /> PDF</a>{r?.lockedAt ? <button disabled={busy === q.id} onClick={() => void revise(q)}><RefreshCw size={14} /> Yeni Revizyon</button> : <><button className="ghost" onClick={() => navigate(`/logo-kalem-quotes/${q.id}/edit`)}><Pencil size={14} /> Düzenle</button><button disabled={busy === q.id} onClick={() => void send(q)}><Send size={14} /> Gönder</button></>}<button className="ghost" onClick={() => setProcess(q)}><History size={14} /> Süreç</button></div></td></tr>;
      })}</tbody></table></div>}
    </section> : <section className="card"><div className="section-heading"><div><h3>Logo-Kalem Ürün Kataloğu</h3><p>Teklif editöründe seçilebilen lisans, modül ve hizmet başlangıç verileri.</p></div><button onClick={() => setCatalogEdit('new')}><Plus size={15} /> Ürün Ekle</button></div><div className="table-wrap"><table><thead><tr><th>Kod</th><th>Kategori</th><th>Ürün / Hizmet</th><th>Periyot</th><th>Liste fiyatı</th><th>Durum</th><th></th></tr></thead><tbody>{catalog.map((item) => <tr key={item.id}><td><strong>{item.code}</strong></td><td>{item.category}</td><td><strong>{item.nameTr}</strong><small>{item.descriptionTr}</small></td><td>{item.billingPeriod}</td><td>{item.defaultPrice} {item.currency}</td><td><span className={`badge ${item.active ? 'ACTIVE' : 'REJECTED'}`}>{item.active ? 'Aktif' : 'Pasif'}</span></td><td><button className="ghost" onClick={() => setCatalogEdit(item)}><Pencil size={14} /> Düzenle</button></td></tr>)}</tbody></table></div></section>}
    {process && <ProcessModal quote={process} onClose={() => setProcess(null)} onChanged={reload} />}
    {catalogEdit && <CatalogModal item={catalogEdit === 'new' ? undefined : catalogEdit} onClose={() => setCatalogEdit(null)} onSaved={() => { setCatalogEdit(null); reload(); }} />}
  </>;
}

function ProcessModal({ quote, onClose, onChanged }: { quote: LogoKalemQuote; onClose: () => void; onChanged: () => void }) {
  const [activities, setActivities] = useState<QuoteActivity[]>([]); const [revisions, setRevisions] = useState<LogoKalemRevision[]>([]); const [busy, setBusy] = useState(false); const toast = useToast();
  useEffect(() => { void Promise.all([api.logoKalem.activities(quote.id), api.logoKalem.revisions(quote.id)]).then(([a, r]) => { setActivities(a); setRevisions(r); }).catch(() => { setActivities([]); setRevisions([]); }); }, [quote.id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await api.logoKalem.addActivity(quote.id, { type: String(form.get('type')) as QuoteActivityType, status: String(form.get('status')) as QuoteStatus, note: String(form.get('note')), activityAt: String(form.get('activityAt')) }); toast.success('Süreç hareketi kaydedildi'); setActivities(await api.logoKalem.activities(quote.id)); onChanged(); event.currentTarget.reset(); } catch (e) { toast.error(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <div className="form-modal-backdrop"><div className="form-modal lk-process" role="dialog" aria-modal="true"><div className="form-modal-header"><div><span className="page-eyebrow">Satış süreci</span><h3>{quote.customerName}</h3><p>{quote.baseNumber}</p></div><button className="modal-close" onClick={onClose}><X size={18} /></button></div><div className="form-modal-body"><div className="lk-revisions"><strong>Belge revizyonları</strong>{revisions.map((r) => <a key={r.id} href={api.logoKalem.pdfUrl(quote.id, r.id)} target="_blank" rel="noreferrer"><span>R{String(r.revisionNumber).padStart(2, '0')} · {r.language.toUpperCase()}</span><small>{r.lockedAt ? `Kilitli · ${new Date(r.lockedAt).toLocaleString('tr-TR')}` : 'Aktif taslak'}</small><Download size={14} /></a>)}</div><form className="lk-process-form" onSubmit={submit}><label className="field">Hareket<select name="type" defaultValue="PHONE_CALL"><option value="PHONE_CALL">Telefon</option><option value="VISIT">Ziyaret</option><option value="MEETING">Toplantı</option><option value="NOTE">Not</option><option value="STATUS_CHANGE">Durum değişikliği</option></select></label><label className="field">Durum<select name="status" defaultValue={quote.status}>{Object.entries(statusLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><label className="field">Tarih<input name="activityAt" type="datetime-local" defaultValue={new Date(Date.now() - new Date().getTimezoneOffset() * 60000).toISOString().slice(0, 16)} /></label><label className="field full">Görüşme notu<textarea name="note" required minLength={2} /></label><button disabled={busy}>Hareketi Kaydet</button></form><div className="lk-timeline">{activities.map((a) => <article key={a.id}><span /><div><strong>{a.note}</strong><small>{statusLabels[a.status ?? quote.status]} · {new Date(a.activityAt).toLocaleString('tr-TR')} · {a.createdByEmail || 'Sistem'}</small></div></article>)}</div></div></div></div>;
}

function CatalogModal({ item, onClose, onSaved }: { item?: LogoKalemCatalogItem; onClose: () => void; onSaved: () => void }) {
  const toast = useToast(); const [busy, setBusy] = useState(false); const value = item ?? blankCatalog;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const payload = { code: String(f.get('code')), category: String(f.get('category')), nameTr: String(f.get('nameTr')), nameAz: String(f.get('nameAz')), nameEn: String(f.get('nameEn')), descriptionTr: String(f.get('descriptionTr')), unit: String(f.get('unit')), billingPeriod: String(f.get('billingPeriod')) as LogoKalemCatalogItem['billingPeriod'], defaultPrice: String(f.get('defaultPrice')), currency: String(f.get('currency')), active: f.get('active') === 'on', sortOrder: Number(f.get('sortOrder')) }; setBusy(true); try { item ? await api.logoKalem.updateCatalog(item.id, payload) : await api.logoKalem.createCatalog(payload); toast.success('Katalog kaydı güncellendi'); onSaved(); } catch (e) { toast.error(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <div className="form-modal-backdrop"><div className="form-modal catalog-modal"><div className="form-modal-header"><div><span className="page-eyebrow">Ürün kataloğu</span><h3>{item ? 'Katalog kaydını düzenle' : 'Yeni ürün / hizmet'}</h3></div><button className="modal-close" onClick={onClose}><X size={18} /></button></div><form onSubmit={submit}><div className="form-modal-body"><div className="form-grid"><label className="field">Kod<input name="code" required defaultValue={value.code} /></label><label className="field">Kategori<input name="category" required defaultValue={value.category} /></label><label className="field">Türkçe ad<input name="nameTr" required defaultValue={value.nameTr} /></label><label className="field">Azerbaycanca ad<input name="nameAz" defaultValue={value.nameAz} /></label><label className="field">İngilizce ad<input name="nameEn" defaultValue={value.nameEn} /></label><label className="field">Birim<input name="unit" defaultValue={value.unit} /></label><label className="field">Periyot<select name="billingPeriod" defaultValue={value.billingPeriod}><option value="ONE_TIME">Tek seferlik</option><option value="MONTHLY">Aylık</option><option value="ANNUAL">Yıllık</option></select></label><label className="field">Fiyat<input name="defaultPrice" inputMode="decimal" required defaultValue={value.defaultPrice} /></label><label className="field">Para birimi<input name="currency" required defaultValue={value.currency} /></label><label className="field">Sıra<input name="sortOrder" type="number" defaultValue={value.sortOrder} /></label><label className="field full">Açıklama<textarea name="descriptionTr" defaultValue={value.descriptionTr} /></label><label className="toggle-row full"><input name="active" type="checkbox" defaultChecked={value.active} /> Aktif katalog kaydı</label></div></div><div className="form-modal-footer"><button className="ghost" type="button" onClick={onClose}>Vazgeç</button><button disabled={busy}>{busy ? 'Kaydediliyor…' : 'Kaydet'}</button></div></form></div></div>;
}
